environment:
  op:
    url: "http://op-wb.tudoucloud.com/uaa/oauth/token"
    headers:
      Content-Type: "application/json;charset=UTF-8"
    # 请勿修改key，会导致登陆失败
    data:
      account_type: "mobile"
      client_id: "saas_op"
      client_secret: "dc278c7ba8b3ddedbde7361fcedb70ee"
      grant_type: "password"
      mobile: "18192408293"
      password: "eede6d66c93b0340342c18f8c5c76a87"
      scope: "trust"
      username: "18192408293"
  cp:
    url: "http://wb.tudoucloud.com/uaa/oauth/token"
    headers:
      Content-Type: "application/json;charset=UTF-8"
    # 请勿修改key，会导致登陆失败
    data:
      account_type: "mobile"
      client_id: "saas_cp"
      client_secret: "cd342c7baed3dd3b55e7361fcedb88eh"
      grant_type: "password"
      mobile: "18603015137"
      password: "737cec5e3ca2a2fb367fbedf4965fbc6"
      scope: "trust"
      username: "18603015137"

api_host:
  - http://kubeos.tudoucloud.com
  - http://kube.tudoucloud.com
  - http://datagaea.tudoucloud.com
  - http://ai.tudoucloud.com
  - http://3dm.tudoucloud.com
  - http://wb.tudoucloud.com

email:
  smtpserver: smtp.qq.com
  sender: 948080782@qq.com
  password: gboboxzhptgubcag
  receiver: 948080782@qq.com

databases:
  host: 127.0.0.1
  user: root
  port: 3306
  passwd: 123456
  db: pytest_auto_uitest_apitest
  charset: utf8

testers:
  - 张涛
  - 严雪娇

delete_report_on_off:
  - "on"
  - "off"
run_report_on_off:
  - "on"
  - "off"
send_email_on_off:
  - "on"
  - "off"
open_report_on_off:
  - "on"
  - "off"
databases_on_off:
  - "on"
  - "off"
send_dingding_news_on_off:
  - "on"
  - "off"

redis:
  host: 127.0.0.1
  port: 6379

dingding:
  secret: "SEC14d75e31de633eaec66f15267ff75f1def52bd32d961798750cca780ff88dafe"
  webhook: "https://oapi.dingtalk.com/robot/send?access_token=50d6b1a92b4db2f06419e621978e8b47fe01b23d17e11f93e407ec2bab7100e8"
