environment:
  op:
    url: "http://op-wb.tudoucloud.com/uaa/oauth/token"
    headers:
      Content-Type: "application/json;charset=UTF-8"
    # 请勿修改key，会导致登陆失败
    data:
      account_type: "mobile"
      client_id: "saas_op"
      client_secret: "xxx"
      grant_type: "password"
      mobile: "xxx"
      password: "xxx"
      scope: "trust"
      username: "xxx"
  cp:
    url: "http://wb.tudoucloud.com/uaa/oauth/token"
    headers:
      Content-Type: "application/json;charset=UTF-8"
    # 请勿修改key，会导致登陆失败
    data:
      account_type: "mobile"
      client_id: "saas_cp"
      client_secret: "xxx"
      grant_type: "password"
      mobile: "xxx"
      password: "xxx"
      scope: "trust"
      username: "xxx"

api_host:
  - http://kubeos.tudoucloud.com
  - http://kube.tudoucloud.com
  - http://datagaea.tudoucloud.com
  - http://ai.tudoucloud.com
  - http://3dm.tudoucloud.com
  - http://wb.tudoucloud.com

email:
  smtpserver: smtp.qq.com
  sender: xx@qq.com
  password: xxx
  receiver: xx@qq.com

databases:
  host: 127.0.0.1
  user: root
  port: 3306
  passwd: 123456
  db: auto_test
  charset: utf8

testers:
  - 张三
  - 李四

delete_report_on_off:
  - "on"
  - "off"
run_report_on_off:
  - "on"
  - "off"
send_email_on_off:
  - "on"
  - "off"
open_report_on_off:
  - "on"
  - "off"
databases_on_off:
  - "on"
  - "off"
send_dingding_news_on_off:
  - "on"
  - "off"

redis:
  host: 127.0.0.1
  port: 6379

dingding:
  secret: "xxx"
  webhook: "https://oapi.dingtalk.com/robot/send?access_token=xxx"
